CREATE TABLE apps (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE,
    created timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    repo text NOT NULL,
    build text DEFAULT 'build.sh'
);

CREATE TRIGGER update_timestamp
BEFORE UPDATE
ON apps
FOR EACH ROW EXECUTE FUNCTION update_timestamp();
