CREATE TABLE clients (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection uuid NOT NULL UNIQUE,
    connected boolean NOT NULL DEFAULT True,
    created timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    target boolean NOT NULL,
    app text NOT NULL,
    name text NOT NULL,
    tags text[]
);

CREATE FUNCTION update_timestamp() RETURNS trigger AS $$
    BEGIN
        NEW.updated := CURRENT_TIMESTAMP;
        RETURN NEW;
    END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_timestamp
BEFORE UPDATE
ON clients
FOR EACH ROW EXECUTE FUNCTION update_timestamp();
